### ISSUE TITLE
`unnecessary braces` error while compiling

### ISSUE THREAD

**Issue by acelot** [davidpdrsn/juniper-from-schema#127]
I have very simple GraphQL schema:

```graphql
schema {
    query: Query
}

type Query {
    ping: Boolean! @juniper(infallible: true, ownership: "owned")
}
```

```rust
use juniper_from_schema::graphql_schema_from_file;
use crate::resources::Resources;

graphql_schema_from_file!("schema.graphql");

pub struct Query;

pub struct Context {
    resources: Resources,
}

impl juniper::Context for Context {}
```

i get error like this when compiling:

```
warning: unnecessary braces around block return value
 --> src/graphql/schema.rs:4:1
  |
4 | graphql_schema_from_file!("schema.graphql");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these braces
  |
  = note: `#[warn(unused_braces)]` on by default
```

What does it mean?

My Cargo.toml:

```toml
[dependencies]
juniper = { git = "https://github.com/graphql-rust/juniper", branch = "master" }
juniper-from-schema = { git = "https://github.com/davidpdrsn/juniper-from-schema", branch = "master" }
```
